/**
 * Turns Map Editor authoring state into a real, self-contained TypeScript
 * `MapHexDef[]` source file — matching the existing hand-authored convention
 * (e.g. `data/maps/mission1.ts`'s `MISSION1_MAP`) rather than a JSON blob.
 *
 * The overlay image (if any) is deliberately NOT embedded as a base64 blob in
 * the generated source — it's downloaded as a real, separate image file the
 * author drops into `public/assets/maps/`, and the `.ts` file just holds a
 * short `/assets/maps/<slug>.<ext>` path string, matching how every other
 * piece of art in this project (`data/hexArt.ts`'s `TERRAIN_ART`, etc.) is
 * referenced by URL rather than inlined.
 */
import type { MapHexDef } from '../../engine/types';
import { slugify, toSource } from './tsSource';

export interface MapEditorAuthoredState {
  mapName: string;
  mapNumber: number;
  hexes: MapHexDef[];
  /** See `MapCatalogEntry.overlayImage` — a data: URL, if the map was traced/authored with one. */
  overlayUrl?: string | null;
}

/** `data:image/png;base64,...` -> `png` (also handles `jpeg`->`jpg`, `svg+xml`->`svg`); defaults to `png`. */
function extensionForDataUrl(dataUrl: string): string {
  const subtype = dataUrl.match(/^data:image\/([a-zA-Z0-9+.-]+);base64,/)?.[1]?.toLowerCase();
  const aliases: Record<string, string> = { jpeg: 'jpg', 'svg+xml': 'svg' };
  return (subtype && (aliases[subtype] ?? subtype)) || 'png';
}

/** Produce the full, self-contained TypeScript `MapHexDef[]` source text. */
export function emitMapSource(state: MapEditorAuthoredState): string {
  const id = slugify(state.mapName, 'map');
  const constName = id.toUpperCase().replace(/-/g, '_') + '_MAP';
  const overlayConstName = id.toUpperCase().replace(/-/g, '_') + '_OVERLAY';
  const hasOverlay = !!state.overlayUrl;
  const overlayFileName = hasOverlay ? `${id}.${extensionForDataUrl(state.overlayUrl!)}` : null;
  const overlayPath = hasOverlay ? `/assets/maps/${overlayFileName}` : null;

  return `/**
 * ${state.mapName || 'Untitled Map'} (Map #${state.mapNumber})
 * Generated by the Map Editor — a self-contained terrain map.
 *
 * To make this map available to the Mission Editor and real Missions:
 *  1. Drop this file into src/data/maps/.${
   hasOverlay
     ? `\n *  2. Save the downloaded overlay image (\`${overlayFileName}\`, downloaded alongside this
 *     file) into public/assets/maps/.
 *  3. Import`
     : '\n *  2. Import'
 } \`${constName}\`${hasOverlay ? ` and \`${overlayConstName}\`` : ''} in
 *     src/data/maps/catalog.ts and add an entry:
 *     ${id}: { id: '${id}', name: ${JSON.stringify(state.mapName)}, hexes: ${constName}${
       hasOverlay ? `, overlayImage: ${overlayConstName}` : ''
     } },
 */
import type { MapHexDef } from '../../engine/types';
${
  hasOverlay
    ? `\n/** Real gameplay art (Map Editor "Overlay mode") — a real file at public${overlayPath}, not embedded data. */\nexport const ${overlayConstName}: string = ${toSource(overlayPath)};\n`
    : ''
}
export const ${constName}: MapHexDef[] = ${toSource(state.hexes)};
`;
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Generate the source and trigger a browser download of it — plus, if an
 * overlay is set, a SECOND download of the real image file (extracted from
 * the working data: URL), named to match the path the source just referenced.
 */
export function downloadMapSource(state: MapEditorAuthoredState): void {
  let source: string;
  try {
    source = emitMapSource(state);
  } catch (err) {
    window.alert(err instanceof Error ? err.message : String(err));
    return;
  }
  downloadBlob(new Blob([source], { type: 'text/typescript' }), `${slugify(state.mapName, 'map')}.ts`);

  if (state.overlayUrl) {
    const filename = `${slugify(state.mapName, 'map')}.${extensionForDataUrl(state.overlayUrl)}`;
    fetch(state.overlayUrl)
      .then((r) => r.blob())
      .then((blob) => downloadBlob(blob, filename));
  }
}
